---
- block:

    - name: Update apt package index
      apt:
        update_cache: yes
      when: ansible_distribution == 'Debian'
      # This is a lie, but necessary for Idempotence test
      changed_when: False

    # Break the loop once the first package name/URL in the list is found to be installed.
    # The yum module (which wraps the yum command) uses rc=126 for package not
    # found, or 0 for changed / already installed.
    - name: Install EPEL Release
      yum:
        name: "{{ item }}"
        state: present
        # dnf/yum4 registered results not implemented yet
        use_backend: yum
      register: epel
      when:
        - (ansible_distribution == 'CentOS') or (ansible_distribution == 'RedHat')
        # Works for both strings and lists to make sure not empty
        - epel_release_packages is defined
        - epel_release_packages is not none
        - epel_release_packages | length > 0
        - ( ansible_loop.first ) or (epel.rc == 126)
      failed_when: (epel.rc not in [0,126]) or
                   (( ansible_loop.last ) and (epel.rc == 126))
      # Cast a single string as a list so that the loop will work.
      # This will also convert a list to a list with 1 list in it, so flatten it
     # so that the yum task will only operate on 1 item at a time.
      loop: "{{ lookup('vars', 'epel_release_packages', wantlist=True) | flatten }}"
      loop_control:
        extended: True

    - name: Install prerequisites
      package:
        name: '{{ pulp_preq_packages }}'
        state: present

    - name: Disable SELinux (Pulp 3 is currently incompatible with SELinux)
      selinux:
        policy: targeted
        state: permissive
      when: ansible_os_family == 'RedHat'

    # Become root so as to search paths like /usr/sbin.
    - name: Find the nologin executable
      command: which nologin
      changed_when: False
      check_mode: False
      register: result

    - name: Make sure {{ pulp_group }} group exists
      group:
        name: '{{ pulp_group }}'
        gid: '{{ pulp_group_id }}'
        state: present
        system: true

    # If we do not create it here, but it is separate from developer_user,
    # the following task would create it incorrectly with default settings.
    - name: Create user {{ pulp_user }}
      user:
        name: '{{ pulp_user }}'
        uid: '{{ pulp_user_id }}'
        shell: '{{ result.stdout.strip() }}'
        home: '{{ pulp_user_home }}'
        system: true
        groups:
          - '{{ pulp_group }}'
        append: true
      # The check implicitly does an or for this check:
      # developer_user is not defined
      when: pulp_user != developer_user|default('')

    - name: Add user {{ pulp_user }} to extra groups
      user:
        name: '{{ pulp_user }}'
        groups: '{{ pulp_extra_groups }}'
        append: true
      when: pulp_extra_groups is defined

    - name: Add user {{ developer_user }} to {{ pulp_group }} group
      user:
        name: '{{ developer_user }}'
        groups:
          - '{{ pulp_group }}'
        append: true
      when: developer_user is defined

    - name: Reset ssh conn to allow user changes to affect when ssh user and pulp user are the same
      meta: reset_connection

    - name: Create cache dir for Pulp
      file:
        path: '{{ pulp_cache_dir }}'
        state: directory
        owner: '{{ pulp_user }}'
        group: '{{ pulp_group }}'
        mode: "u+rwx,g+rwx,o+rx"

    - name: Create pulp install dir
      file:
        path: '{{ pulp_install_dir }}'
        state: directory
        owner: '{{ pulp_user }}'
        group: '{{ pulp_group }}'

    # If so, owner will be apache
    - name: Check if we have Pulp 2 installed
      stat:
        path: "{{ pulp_user_home }}"
      register: pulp_user_home_stat

    - name: Fix permissions if Pulp 2 is already installed (https://pulp.plan.io/issues/5553#note-5)
      block:
        - name: Add user 'apache' to '{{ pulp_group }}' group if it exists
          user:
            name: apache
            groups:
              - '{{ pulp_group }}'
            append: true

        - name: Set permissions on '{{ pulp_user_home }}' if pulp2 is installed
          file:
            path: '{{ pulp_user_home }}'
            state: directory
            group: '{{ pulp_group }}'
            # The uppercase X says "only make dirs executable, not files"
            mode: "g+rwX"
            recurse: true

        - name: Find subdirs without setgid
          command: "find {{ pulp_user_home }} -type d -perm -g-s"
          changed_when: false
          check_mode: false
          register: dirs_needing_setgid

        # We need dirs to have setgid so that newly generated files by Pulp 2
        # have the pulp group rather than the apache group.
        # But you cannot make chmod or the file module only do setgid for dirs
        # and not files.
        - name: Set setgid on the {{ pulp_user_home }} subdirs
          file:
            path: "{{ item }}"
            mode: g+s
          with_items: "{{ dirs_needing_setgid.stdout_lines }}"
          when: dirs_needing_setgid.stdout | length > 0

      when: pulp_user_home_stat.stat.pw_name == "apache"

    - name: Install packages needed for source install
      package:
        name:
          - git
        state: present
      register: result
      until: result is succeeded

    # We are purposely running this before the venv is created, since
    # if we are using system-wide packages, it could cause duplicate
    # python packages to be installed.
    # Note: We would do a static import like in pulp-database, but
    # looping does not work with it, so we do a dynamic include.
    - name: Include plugins prereq roles
      include_role:
        name: "{{ item.value.prereq_role }}"
      with_dict: "{{ pulp_install_plugins }}"
      when: item.value.prereq_role is defined

  become: true

- block:

    # Hack for use system-wide packages when enabled by user - Must be first usage of virtualenv
    - name: Create a venv with system-wide packages setting if the venv does not exist
      pip:
        name: pip  # specifying pip is a safe hack to create the venv, since pip is automatically in every new venv.
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
        virtualenv_site_packages: yes
      when: pulp_use_system_wide_pkgs | bool

    - name: Update any existing venv to allow system-wide packages
      lineinfile:
        path: "{{ pulp_install_dir }}/pyvenv.cfg"
        regexp: '^include-system-site-packages'
        line: "include-system-site-packages = true"
      when: pulp_use_system_wide_pkgs | bool

    - name: Install the prereq_pip_packages
      pip:
        name: '{{ prereq_pip_packages }}'
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      when: prereq_pip_packages | length > 0

    - name: Install pulpcore package via PyPI
      pip:
        name: pulpcore
        # pulp_upgrade true/false -> ansible pip module latest/present ->
        # pip command "install --upgrade"/"install"
        # Commented out because:
        # "version is incompatible with state=latest"
        # But we still need to handle upgrading dependencies.
        # state: "{{ pulp_upgrade | ternary('latest','present') }}"
        version: '{{ pulp_version }}'
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      when: pulp_source_dir is undefined
      notify:
        - Collect static content
        - Restart all Pulp services

    - name: Install pulpcore package from source
      pip:
        name: '{{ pulp_source_dir }}'
        editable: '{{ pulp_pip_editable }}'
        # For this task, `state` has no effect. It installs or upgrades/
        # downgrades to the exact dir's or VCS URL's version regardless.
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      when: pulp_source_dir is defined
      register: result
      # This is a hack. Editable pip installs are always changed, which fails molecule's
      # idempotence test.
      # Unfortunately, this will prevent the handlers from being notified.
      changed_when: result.changed and not pulp_pip_editable
      notify:
        - Collect static content
        - Restart all Pulp services

    # We have to do this separate task, even though the pip module should
    # register the installed version, because when tested (Ansible 2.9, with no
    # changes applied), the registered result from "Install pulpcore package
    # from source" left the version field "null".
    - name: Obtain list of packages & versions in the venv
      pip_package_info:
        clients: "{{ pulp_install_dir }}/bin/pip"
      register: pip_pkgs

    - name: Create constraints file to lock the pulpcore version when plugins are installed
      copy:
        content: "pulpcore=={{ pip_pkgs.packages[pulp_install_dir + '/bin/pip'].pulpcore[0].version }}\n"
        dest: "{{ pulp_install_dir }}/pip_constraints_for_plugins.txt"

    - name: Install Pulp plugins via PyPI
      pip:
        name: '{{ item.key }}'
        # item.upgrade true/false -> ansible pip module latest/present ->
        # pip command "install --upgrade"/"install"
        state: "{{ item.value.upgrade | default(false) | ternary('latest','present','present') }}"
        # TODO: Handle the fact that "version is incompatible with state=latest"
        # through proper means, rather than just telling users not to set both.
        version: '{{ item.value.version | default(omit) }}'
        extra_args: "-c {{ pulp_install_dir }}/pip_constraints_for_plugins.txt"
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      with_dict: '{{ pulp_install_plugins }}'
      when: pulp_install_plugins[item.key].source_dir is undefined
      notify:
        - Collect static content
        - Restart all Pulp services

    - name: Install Pulp plugins from source
      pip:
        name: '{{ item.value.source_dir }}'
        editable: '{{ pulp_pip_editable }}'
        # For this task, `state` has no effect. It installs or upgrades/
        # downgrades to the exact dir's or VCS URL's version regardless.
        state: present
        extra_args: "-c {{ pulp_install_dir }}/pip_constraints_for_plugins.txt"
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      with_dict: '{{ pulp_install_plugins }}'
      when: item.value.source_dir is defined
      register: result
      # This is a hack. Editable pip installs are always changed, which fails molecule's
      # idempotence test.
      # Unfortunately, this will prevent the handlers from being notified.
      changed_when: result.changed and not pulp_pip_editable
      notify:
        - Collect static content
        - Restart all Pulp services

  become: true
  become_user: '{{ pulp_user }}'
...
