---
- hosts: localhost
  connection: local
  vars:
    pulp_secret_key: "unsafe_default"
    pulp_default_admin_password: password
#    ansible_python_interpreter: "/usr/bin/python3"
    pulp_install_plugins: 
      pulp-ansible:
         app_label:"pulp_ansible"
  
  roles:
    - pulp-database
    - pulp-workers
    - pulp-resource-manager
    - pulp-webserver
    - pulp-content
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
